```{r Install required packages}
install.packages('metafor')
install.packages('meta')
install.packages('weightr')
```
```{r Load required packages}
library(metafor)
library(meta)
library(weightr)
```
```{r Read data files}
setwd("your working directory")
dat=read.csv("1stauthorpubyear.csv",header=T,sep=",")
```
```{r Calculate overall and subgroup effect sizes}
ies=escalc(xi=cases,ni=total,measure="PR",data=dat)
pes=rma(yi,vi,data=ies,method="DL",weighted=TRUE, slab=paste(author, year, sep=", "))
pes.mal1=rma(yi,vi,data=ies,subset=moderatora=="level1",method="DL")
pes.mal2=rma(yi,vi,data=ies,subset=moderatora=="level2",method="DL")
print(pes)
print(pes.mal1)
print(pes.mal2)
```
```{r Forest plot using metaprop}
#If you want to create the forest plot automatically, use the forest function in the meta package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
pes.forest=metaprop(cases,total,author,data=dat,byvar=moderatora,sm="PRAW",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,title="")
png("forestplot_meta.png",width=1000,height=1000)
forest(pes.forest,
       xlim = c(0,1), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey")
dev.off()
```
```{r Forest plot using metafor}
#If you want to create the forest plot manually, use the forest function in the metafor package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
png("forestplot_metafor.png",width=1000,height=1000)
forest(pes,
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.4),
       rows=c(25:13,7.6:2.6),
       at=c(seq(from=0,to=1.1,by=0.2)),  
       refline=pes$b, 
       ylim=c(-2,30), 
       xlim=c(-2,2.1), 
       cex=0.8, 
       font=6,
       main="Effect size by moderator A (RE Model)",
       xlab="Proportion"
       )
text(-2, 29,pos=4,cex=0.8,font=6,"Author(s), Year")
text(-2,c(8.9,26.3),pos=4, cex=0.8,font=6,c("mal2", "mal1")) 
text(c(-1, -0.6), 29,pos=4,cex=0.8,font=6,c("Cases", "Total"))
text(1.65,29,pos=4,font=6,cex=0.8,"Proportion [95% CI]")
text(-2,-1.1,pos=4,cex=0.8,font=1, bquote(paste("All studies(Q = ",.(formatC(pes$QE, format="f")), ", df = ", .(pes$k - pes$p),", p = ", .(formatC(pes$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes$I2, format="f")), "%",")")))
text(-2,11.4,pos=4,cex=0.8,font=1, bquote(paste("Subtotal(Q = ",.(formatC(pes.mal1$QE, format="f")), ", df = ", .(pes.mal1$k - pes.mal1$p),", p = ", .(formatC(pes.mal1$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.mal1$I2, format="f")), "%",")")))
text(-2,1.1,pos=4,cex=0.8,font=3, bquote(paste("Subtotal(Q = ",.(formatC(pes.mal2$QE, format="f")),", df = ", .(pes.mal2$k - pes.mal2$p), ", p = ", .(formatC(pes.mal2$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.mal2$I2, format="f")), "%",")")))
addpoly(pes.mal1, row=11.4, cex=0.8,font=1, mlab="")
addpoly(pes.mal2, row=1.1, cex=0.8, font=1, mlab="")
dev.off()
```
```{r Baujat plot}
baujat(pes)
```
```{r Diagnostic tests with logit transformation}
inf=influence(pes)
plot(inf)
```
```{r Leave-one-out analysis}
leave1out(pes)
```
```{r Subgroup analysis}
#If you assume a common among-study variance component across subgroups (pool within-group estimates of tau-squared), then remove the "#" sign before the following two lines.
subganal.moderatora=rma(yi,vi,data=ies,mods=~moderatora,method="DL")
print(subganal.moderatora)
#If you do not assume a common among-study variance component across subgroups (do not pool within-group estimates of tau-squared), then remove the "#" sign before the following three lines. This is the option used by RevMan.
#dat.diffvar= data.frame(estimate=c(pes.mal1$b, pes.mal2$b),stderror=c(pes.mal1$se, pes.mal2$se),moderatora = c("mal1","mal2"), tau2=round(c(pes.mal1$tau2, pes.mal2$tau2),3))
#subganal.moderatora=rma(estimate, sei=stderror, mods = ~ moderatora, method="FE", data=dat.diffvar)
#print(subganal.moderatora)
```
```{r Meta-regression}
metareg.mod1=rma(yi,vi,data=ies,mods=~moderator1,method="REML",test="z")
print(metareg.mod1)
```
```{r Bubble plot}
#Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
pes.bb=predict(metareg.mod1,newmods=c(0:40))
plot(ies$moderator1,ies$yi,cex=size,pch=1,xlab="Moderator 1", ylab="Proportion",las=1)
lines(0:40,pes.bb$pred)
lines(0:40,pes.bb$ci.lb,lty="dashed")
lines(0:40,pes.bb$ci.ub,lty="dashed")
ids <- c(1:6)
pos <- c(1)
text(ies$moderator1[ids], transf.ilogit(ies$yi)[ids], ids, cex=0.9, pos=pos)
```
```{r Funnel plot}
png("funnel.png",width=1000,height=1000)
funnel(pes)
dev.off()
```
```{r Trim and fill plot}
png("trimfill.png",width=1000,height=1000)
pes.trimfill=trimfill(pes)
funnel(pes.trimfill)
dev.off()
print(pes.trimfill)
```
```{r Egger's regression test}
regtest(pes,model="lm",predictor="sei")
```
```{r Rank correlation}
ranktest(pes)
```
```{r Failsafe N test}
fsn(yi,vi,data=ies)
```
```{r Vevea and Hedges Weight-Function Model}
weightfunct(ies$yi,ies$vi,steps=0.05) 
```

