```{r Install required packages}
#install.packages('metafor')
#install.packages('meta')
#install.packages('weightr')
```
```{r Load required packages}
library(metafor)
library(meta)
library(weightr)
```
```{r Read data files}
setwd("D:/mygithubproj/metaprops")
dat=read.csv("ammirati.csv",header=T,sep=",")
```
```{r Calculate overall effect size and subgroup effect sizes with Freeman-Tukey double arcsine transformation}
ies.ft=escalc(measure="PFT",xi=cases,ni=total,data=dat, add=0)
pes.ft=rma(yi,vi,data=ies.ft,method="FE",weighted=TRUE)
pes.ft.endoscopy=rma(yi,vi,data=ies.ft,subset=procedure=="endoscopy",method="FE")
pes.ft.microscopy=rma(yi,vi,data=ies.ft,subset=procedure=="microscopy",method="FE")
pes=predict(pes.ft,transf=transf.ipft.hm,targ=list(ni=dat$total))
pes.endoscopy=predict(pes.ft.endoscopy,transf=transf.ipft.hm,targ=list(ni=dat$total))
pes.microscopy=predict(pes.ft.microscopy,transf=transf.ipft.hm,targ=list(ni=dat$total))
##pes=predict(pes.ft,transf=transf.iarcsin)
##pes.endoscopy=predict(pes.ft.endoscopy,transf=transf.iarcsin)
##pes.microscopy=predict(pes.ft.microscopy,transf=transf.iarcsin)
print(pes,digits=4)
print(pes.endoscopy,digits=4)
print(pes.microscopy,digits=4)
```
```{r Forest plot with double arcsine transformation using metaprop}
pes.forest=metaprop(cases,total,author,data=dat,byvar=procedure,sm="PFT",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,title="")
png("forestplot_ft_meta.png",width=1000,height=1000)
forest(pes.forest,
       xlim = c(0,0.5), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=TRUE,
       comb.random=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey",
       digits=4)
dev.off()
```
```{r Forest plot with double arcsine transformation using metafor}
png("forestplot_ft_metafor.png",width=1000,height=1000)
ies.summary=summary(ies.ft,transf=transf.ipft,ni=dat$total)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author, dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.5),
       rows=c(36:20, 13:2),
       ylim=c(-2,41),
       xlim=c(-2,2.1),
       at=c(seq(from=0,to=0.5,by=0.1)), 
       refline=pes$pred,
       cex=1,
       font=6,
       main="Effect size by moderator a (FE model)",
       xlab="Proportion"
       )
text(-2, 41,pos=4,cex=1,font=6,"Author(s), Year")
text(-2,c(14.5,37.5),pos=4, cex=1,font=6,c("Microscopy", "Endoscopy"))
text(c(-0.9,-0.6), 41,pos=4,cex=1,font=6,c("Cases", "Total"))
text(1.6,41,pos=4,font=6,cex=1,"Proportion [95% CI]")
addpoly(pes.endoscopy$pred,ci.lb=pes.endoscopy$ci.lb,ci.ub=pes.endoscopy$ci.ub,row=18.5,digits=4,cex=0.8,mlab="")
addpoly(pes.microscopy$pred,ci.lb=pes.microscopy$ci.lb,ci.ub=pes.microscopy$ci.ub,row=0.5,digits=4,cex=0.8,mlab="")
addpoly(pes$pred,ci.lb=pes$ci.lb,ci.ub=pes$ci.ub,row=-3,digits=4,cex=0.8,mlab="")
text(-2,-3,pos=4,cex=0.8,bquote(paste("All studies (Q = ",.(formatC(pes.ft$QE, digits=1, format="f")), ", df = ", .(pes.ft$k - pes.ft$p),", p = ", .(formatC(pes.ft$QEp, digits=2, format="f")), "; ", I^2, " = ",.(formatC(pes.ft$I2, digits=1, format="f")), "%",")")))
text(-2,18.5,pos=4,cex=0.8,bquote(paste("Subtotal(Q = ",.(formatC(pes.ft.endoscopy$QE, digits=1, format="f")), ", df = ", .(pes.ft.endoscopy$k - pes.ft.endoscopy$p),", p = ", .(formatC(pes.ft.endoscopy$QEp, digits=2, format="f")),"; ", I^2, " = ",.(formatC(pes.ft.endoscopy$I2, digits=1, format="f")), "%",")")))
text(-2,0.5,pos=4,cex=0.8,bquote(paste("Subtotal(Q = ",.(formatC(pes.ft.microscopy$QE, digits=1, format="f")),", df = ", .(pes.ft.microscopy$k - pes.ft.microscopy$p), ", p = ", .(formatC(pes.ft.microscopy$QEp, digits=2, format="f")), "; ", I^2, " = ",.(formatC(pes.ft.microscopy$I2, digits=1, format="f")), "%",")")))
abline(h=-2)
```
```{r Heterogeneity test with double arcsine transformation}
print(pes.ft,digits=2)
print(pes.ft.endoscopy,digits=2)
print(pes.ft.microscopy,digits=2)
```
```{r Baujat plot with double arcsine transformation}
baujat(pes.ft)
```
```{r Diagnostic tests with double arcsine transformation}
inf=influence(pes.ft)
print(inf,digits=2)
plot(inf)
```
```{r Leave-one-out analysis with double artcsine transformation}
pes.leave1out=leave1out(pes.ft,transf=transf.ipft.hm,targ=list(ni=dat$total),digits=4)
print(pes.leave1out)
```
```{r Subgroup analysis with double arcsine transformation}
subganal.procedure=rma(yi,vi, data=ies.ft, mods = ~ procedure, method="FE")
print(subganal.procedure)
#dat.diffvar= data.frame(estimate=c(pes.ft.endoscopy$b, pes.ft.microscopy$b),stderror=c(pes.ft.endoscopy$se, pes.ft.microscopy$se),procedure = c("endoscopy","microscopy"), tau2=round(c(pes.ft.endoscopy$tau2, pes.ft.microscopy$tau2),3))
#subganal.procedure=rma(estimate, sei=stderror, mods = ~ procedure, method="FE", data=dat.diffvar, digits=4)
#print(subganal.procedure,digits=3)
```
```{r Funnel plot with double arcsine transformation}
png("funnel_ft.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a double arcsine transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.ft,yaxis="sei")
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.ft,atransf=transf.ipft.hm,targ=list(ni=dat$total),yaxis="sei",xlab="Proportion")
dev.off()
```
```{r Trim and fill plot with double arcsine transformation}
pes.trimfill=trimfill(pes.ft)
png("trimfill_ft.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a double arcsine transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.trimfill)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.trimfill,atransf=transf.ipft.hm,targ=list(ni=dat$total),yaxis="sei",xlab="Proportion")
dev.off()
pes.adjusted=predict(pes.trimfill,transf=transf.ipft.hm,targ=list(ni=dat$total))
print(pes.adjusted,digits=4)
```
```{r Egger's regression test with double arcsine transformation}
regtest(pes.ft,model="lm",predictor="sei")
```
```{r Rank correlation with double arcsine transformation}
ranktest(pes.ft)
```
```{r Vevea and Hedges Weight-Function Model with double arcsine transformation}
weightfunct(ies.ft$yi,ies.ft$vi,steps=0.05)
```





