```{r load required packages}
library(metafor)
library(meta)
library(weightr)
```
```{r read data files}
dat=read.csv("D:\\mydata\\wu.csv",header=T,sep=",")
```
```{r calculate overall effect size and subgroup es using the logit transformation}
#note I changed transf.ies to ies.logit
ies.logit=escalc(xi=cases,ni=total,measure="PLO",data=dat)
#note I changed transf.pes to pes.logit
pes.logit=rma(yi,vi,data=ies.logit,method="DL",weighted=TRUE)
#pes=pooled effect size that has been transformed back
pes=predict(pes.logit,transf=transf.ilogit,digits=5)
#note I change pes.m to pes.birthcohort, pes.n to pes.others
pes.logit.birthcohort=rma(yi,vi,data=ies.logit,subset=studytype=="Birth cohort",method="DL")
pes.birthcohort=predict(pes.logit.birthcohort,transf=transf.ilogit,digits=5)
pes.logit.others=rma(yi,vi,data=ies.logit,subset=studytype=="Others",method="DL")
pes.others=predict(pes.logit.others,transf=transf.ilogit,digits=5)
print(pes,digits=6)
print(pes.birthcohort,digits=6)
print(pes.others,digits=6)
```
```{r forest plot using logit transformation }
pes.forest=summary(ies.logit,transf=transf.ilogit,ni=dat$total)
forest(pes.forest$yi,slab=paste(dat$author,dat$year, sep=", "),ci.lb=pes.forest$ci.lb,ci.ub=pes.forest$ci.ub,
       ylim=c(-5,24),
       xlim=c(-0.005,0.005),
       rows=c(19:14, 8.5:-1.5),
       refline=pes$pred,
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.002,-0.001),
       at=c(seq(from=0,to=0.004,by=0.001)), 
       main="Effect size by study type (RE Model)",
       xlab="Proportion",
       cex=0.8,#overall size
       font=6,
       digits=5)
text(-0.005, 23,pos=4,cex=0.8,font=6,"Author(s), Year")#-2=x,17=y;font=2=bold
text(-0.005,c(10,20.5),pos=4, cex=0.8,font=6,c("Others", "Birth Cohort"))#use c() to posit subgroup lables
text(c(-0.0022,-0.0012), 23,pos=4,cex=0.8,font=6,c("Cases", "Total"))
text(0.003,23,pos=4,font=6,cex=0.8,"Proportion [95% CI]")
addpoly(pes.birthcohort$pred,ci.lb=pes.birthcohort$ci.lb,ci.ub=pes.birthcohort$ci.ub,row=12.7,digits=6,cex=0.7,mlab="")
addpoly(pes.others$pred,ci.lb=pes.others$ci.lb,ci.ub=pes.others$ci.ub,row=-2.5,digits=6,cex=0.7,mlab="")
addpoly(pes$pred,ci.lb=pes$ci.lb,ci.ub=pes$ci.ub,row=-5,digits=6,cex=0.7,mlab="")
text(-0.005,-5,pos=4,cex=0.7,
     bquote(paste("All studies (Q = ",.(formatC(pes.logit$QE, digits=1, format="f")), ", df = ", .(pes.logit$k - pes.logit$p),", p = ", .(formatC(pes.logit$QEp, digits=2, format="f")), 
     "; ", I^2, " = ",.(formatC(pes.logit$I2, digits=1, format="f")), "%",")")))
text(-0.005,12.7,pos=4,cex=0.7,
     bquote(paste("Subtotal(Q = ",.(formatC(pes.logit.birthcohort$QE, digits=1, format="f")), ", df = ", .(pes.logit.birthcohort$k - pes.logit.birthcohort$p),", p = ", .(formatC(pes.logit.birthcohort$QEp, digits=2, format="f")),
     "; ", I^2, " = ",.(formatC(pes.logit.birthcohort$I2, digits=1, format="f")), "%",")")))
text(-0.005,-2.8,pos=4,cex=0.7,
     bquote(paste("Subtotal(Q = ",.(formatC(pes.logit.others$QE, digits=1, format="f")),", df = ", .(pes.logit.others$k - pes.logit.others$p), 
     ", p = ", .(formatC(pes.logit.others$QEp, digits=2, format="f")), 
     "; ", I^2, " = ",.(formatC(pes.logit.others$I2, digits=1, format="f")), "%",")")))
abline(h=-4)
```
```{r check evidence of heterogeneity}
print(pes.logit,digits=2)
```
```{r baujat plot}
baujat(pes.logit)
```
```{r A set of diagnostic tests}
pes.inf=influence(pes.logit)#note I changed inf.pes to pes.inf
print(pes.inf,digits=2)
plot(pes.inf)
```
```{r leave one out analysis}
pes.leave1out=leave1out(pes.logit,transf=transf.ilogit,digits=6)
print(pes.leave1out)
```
```{r subgroup analysis using logit transformation}
#if you assume a common variance
#subganal.studytype=rma(yi,vi, data=ies.logit, mods = ~ studytype, method="DL")
#print(subganal.studytype)
#if you do not assume a common variance
dat.diffvar= data.frame(estimate=c(pes.logit.birthcohort$b, pes.logit.others$b),stderror=c(pes.logit.birthcohort$se, pes.logit.others$se),studytype = c("Birth cohort","Others"), tau2=round(c(pes.logit.birthcohort$tau2, pes.logit.others$tau2),3))
subganal.studytype=rma(estimate, sei=stderror, mods = ~ studytype, method="FE", data=dat.diffvar, digits=4)
print(subganal.studytype,digits=3)
```
```{r funnel plot with logit transformed data}
#tansformed scale:logit odds
funnel(pes.logit,yaxis="sei")
#original scale
#funnel(pes.logit,atransf=transf.ilogit,yaxis="sei",xlab="Proportion")
```
```{r trim and fill with logit transformed data}
pes.trimfill=trimfill(pes.logit)
#transformed scale
#funnel(pes.trimfill)
#original scale
funnel(pes.trimfill,atransf=transf.ilogit,yaxis="sei",xlab="Proportion",digits=6)
#pes.adjusted stands for adjusted values after trim and fill
pes.adjusted=predict(pes.trimfill,transf=transf.ilogit)
print(pes.adjusted,digits=6)
```
```{r Egger's regression test with transformed proportions}
regtest(pes.logit,model="lm",predictor="sei")
```
```{r rank correlation (Kendall's tall) with transformed data}
ranktest(pes.logit)
```
```{r Vevea and Hedges (1995) Weight-Function Model}
weightfunct(ies.logit$yi,ies.logit$vi,steps=0.05)
```
