```{r Install required packages}
#install.packages('metafor')
#install.packages('meta')
#install.packages('weightr')
```
```{r Load required packages}
library(metafor)
library(meta)
library(weightr)
```
```{r Read data files}
setwd("D:/mydata")
dat=read.csv("wu.csv",header=T,sep=",")
```
```{r Calculate overall effect size and subgroup effect sizes with logit transformation}
ies.logit=escalc(xi=cases,ni=total,measure="PLO",data=dat)
pes.logit=rma(yi,vi,data=ies.logit,method="DL",weighted=TRUE)
pes.logit.mal1=rma(yi,vi,data=ies.logit,subset=moderatora=="level1",method="DL")
pes.logit.mal2=rma(yi,vi,data=ies.logit,subset=moderatora=="level2",method="DL")
pes=predict(pes.logit,transf=transf.ilogit)
pes.mal1=predict(pes.logit.mal1,transf=transf.ilogit)
pes.mal2=predict(pes.logit.mal2,transf=transf.ilogit)
print(pes)
print(pes.mal1)
print(pes.mal2)
```
```{r Forest plot with logit transformation using metaprop}
#If you want to create the forest plot automatically, use the forest function in the meta package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
pes.forest=metaprop(cases,total,author,data=dat,byvar=moderatora,sm="PLO",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,title="")
png("forestplot_logit_meta.png",width=1000,height=1000)
forest(pes.forest,
       xlim = c(0,0.005), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey",
       digits=6)
dev.off()
```
```{r Forest plot with logit transformation using metafor}
#If you want to create the forest plot manually, use the forest function in the metafor package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
png("forestplot_logit_metafor.png",width=1000,height=1000)
ies.summary=summary(ies.logit,transf=transf.ilogit,ni=dat$total)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author,dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.002,-0.001),
       rows=c(19:14, 8.5:-1.5),
       at=c(seq(from=0,to=0.004,by=0.001)), 
       refline=pes$pred,
       ylim=c(-5,24),
       xlim=c(-0.005,0.005),
       cex=1,
       font=6,
       main="Effect size by moderator a (RE Model)",
       xlab="Proportion"
       )
text(-0.005, 23,pos=4,cex=1,font=6,"Author(s), Year")
text(-0.005,c(10,20.5),pos=4, cex=1,font=6,c("mal2", "mal1"))
text(c(-0.0022,-0.0012), 23,pos=4,cex=1,font=6,c("Cases", "Total"))
text(0.003,23,pos=4,font=6,cex=1,"Proportion [95% CI]")
addpoly(pes.mal1$pred,ci.lb=pes.mal1$ci.lb,ci.ub=pes.mal1$ci.ub,row=12.7,cex=0.8,mlab="")
addpoly(pes.mal2$pred,ci.lb=pes.mal2$ci.lb,ci.ub=pes.mal2$ci.ub,row=-2.5,cex=0.8,mlab="")
addpoly(pes$pred,ci.lb=pes$ci.lb,ci.ub=pes$ci.ub,row=-5,cex=0.8,mlab="")
text(-0.005,-5,pos=4,cex=0.8, bquote(paste("All studies (Q = ",.(formatC(pes.logit$QE, format="f")), ", df = ", .(pes.logit$k - pes.logit$p),", p = ", .(formatC(pes.logit$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.logit$I2, format="f")), "%",")")))
text(-0.005,12.7,pos=4,cex=0.8, bquote(paste("Subtotal(Q = ",.(formatC(pes.logit.mal1$QE, format="f")), ", df = ", .(pes.logit.mal1$k - pes.logit.mal1$p),", p = ", .(formatC(pes.logit.mal1$QEp, format="f")),"; ", I^2, " = ",.(formatC(pes.logit.mal1$I2, format="f")), "%",")")))
text(-0.005,-2.8,pos=4,cex=0.8, bquote(paste("Subtotal(Q = ",.(formatC(pes.logit.mal2$QE, format="f")),", df = ", .(pes.logit.mal2$k - pes.logit.mal2$p), ", p = ", .(formatC(pes.logit.mal2$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.logit.mal2$I2, format="f")), "%",")")))
abline(h=-4)
dev.off()
```
```{r Heterogeneity test with logit transformation}
print(pes.logit)
print(pes.logit.mal1)
print(pes.logit.mal2)
```
```{r Baujat plot with logit transformation}
baujat(pes.logit)
```
```{r Diagnostic tests with logit transformation}
inf=influence(pes.logit)
print(inf)
plot(inf)
```
```{r Leave-one-out analysis with logit transformation}
pes.leave1out=leave1out(pes.logit,transf=transf.ilogit)
print(pes.leave1out)
```
```{r Subgroup analysis with logit transformation}
#If you assume a common among-study variance component across subgroups (pool within-group estimates of tau-squared), then remove the "#" sign before the following two lines.
#subganal.moderatora=rma(yi,vi, data=ies.logit, mods = ~ moderatora, method="DL")
#print(subganal.moderatora)
#If you do not assume a common among-study variance component across subgroups (do not pool within-group estimates of tau-squared), then remove the "#" sign before the following three lines. This is the option used by RevMan.
dat.diffvar= data.frame(estimate=c(pes.logit.mal1$b, pes.logit.mal2$b),stderror=c(pes.logit.mal1$se, pes.logit.mal2$se),moderatora = c("mal1","mal2"), tau2=round(c(pes.logit.mal1$tau2, pes.logit.mal2$tau2),3))
subganal.moderatora=rma(estimate, sei=stderror, mods = ~ moderatora, method="FE", data=dat.diffvar)
print(subganal.moderatora)
```
```{r Meta-regression with logit transformation}
mreg.mod1=rma(yi,vi,data=ies.logit,mods=~moderator1,method="REML",test="z")
print(mreg.mod1)
```
```{r Bubble plot with logit transformed data}
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
pes=predict(mreg.mod1,newmods=c(0:40),transf=transf.ilogit)
plot(ies.logit$moderator1,transf.ilogit(ies.logit$yi),cex=size,pch=1,xlab="Moderator 1", ylab="Proportion",las=1)
lines(0:40,pes$pred)
lines(0:40,pes$ci.lb,lty="dashed")
lines(0:40,pes$ci.ub,lty="dashed")
ids <- c(1:6)
pos <- c(1)
text(ies.logit$moderator1[ids], transf.ilogit(ies.logit$yi)[ids], ids, cex=0.9, pos=pos)
```
```{r Funnel plot with logit transformation}
png("funnel_logit.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.logit,yaxis="sei")
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.logit,atransf=transf.ilogit,yaxis="sei",xlab="Proportion")
dev.off()
```
```{r Trim and fill plot with logit transformation}
pes.trimfill=trimfill(pes.logit)
png("trimfill_logit.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.trimfill)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.trimfill,atransf=transf.ilogit,yaxis="sei",xlab="Proportion")
dev.off()
pes.adjusted=predict(pes.trimfill,transf=transf.ilogit)
print(pes.adjusted)
```
```{r Egger's regression test with logit transformation}
regtest(pes.logit,model="lm",predictor="sei")
```
```{r Rank correlation with logit transformation}
ranktest(pes.logit)
```
```{r Vevea and Hedges Weight-Function Model with logit transformation}
weightfunct(ies.logit$yi,ies.logit$vi,steps=0.05)
```
