```{r Installing required packages}
install.packages(c("metafor","meta"))#Already installed
```
```{r Loading packages}
library(metafor)
library(meta)
```
```{r Reading in data}
dat=read.csv("D:/data/data_da.csv",header=T,sep=",")
```
```{r Calculating overall summary proportion}
ies.da=escalc(xi=cases,ni=total,measure="PFT",data=dat,add=0)
pes.da=rma(yi,vi,data=ies.da,method="DL",weighted=TRUE)
pes=predict(pes.da,transf=transf.ipft.hm,targ=list(ni=dat$total))
##The authors used the FE model.
##The authors used the arcsine transformation to convert double arcsine transformed proportions back to proportions. The authors did not report the reason for doing so in their article.
##pes=predict(pes.da,transf=transf.iarcsin)
print(pes,digits=6);print(pes.da,digits=6)#Under fixed-effect model, confint () cannot be used.
```
```{r Identifying outliers with residuals}
stud.res=rstudent(pes.da)
abs.z=abs(stud.res$z)
stud.res[order(-abs.z)]
```
```{r Leave-one-out analysis}
pes.leave1out=leave1out(pes.da,transf=transf.ipft.hm,targ=list(ni=dat$total))
print(pes.leave1out,digits=4)
```
```{r Baujat plot}
baujat(pes.da)
```
```{r Diagnostic tests}
inf=influence(pes.da)
print(inf);plot(inf)
```
```{r Removing outliers}
ies.da.noutlier=escalc(xi=cases,ni=total,measure="PFT", data=dat[-c(23),],add=0)
pes.da.noutlier=rma(yi,vi,data=ies.da.noutlier,method="DL",weighted=TRUE)
pes.noutlier=predict(pes.da.noutlier,transf=transf.ipft.hm,targ=list(ni=dat$total))
print(pes,digits=4)
print(pes.noutlier,digits=4)
```
```{r Forest plot using metaprop assuming}
subganal.procedure=rma(yi,vi,data=ies.da,mods=~procedure,method="DL")
pes.summary=metaprop(cases,total,author,data=dat,byvar=procedure,sm="PFT",method.ci="NAsm",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,tau.common=TRUE,tau.preset=sqrt(subganal.procedure$tau2),title="")
png("forestplotmeta.png",width=1000,height=1000)
forest(pes.summary,
       xlim = c(0,1), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       comb.random=TRUE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey",
       digits=6)
dev.off()
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion assuming a common between-study variance component across subgroups}
#Pool within-group estimates of tau-squared
subganal.procedure=rma(yi,vi,data=ies.da,mods=~procedure,method="DL")
pes.da.endoscopy=rma(yi,vi,data=ies.da,mods=~procedure=="microscopy",method="DL")
pes.da.microscopy=rma(yi,vi,data=ies.da,mods=~procedure=="endoscopy",method="DL")
pes.subg.procedure=predict(subganal.procedure,transf=transf.ipft.hm,targ=list(ni=dat$total))
dat.samevar=data.frame(estimate=c((pes.da.endoscopy$b)[1],(pes.da.microscopy$b)[1]),
                       stderror=c((pes.da.endoscopy$se)[1],(pes.da.microscopy$se)[1]),
                       tau2=subganal.procedure$tau2)
pes.da.procedure=rma(estimate,sei=stderror,method="DL",data=dat.samevar) #method="FE or other RE estimators"
pes.procedure=predict(pes.da.procedure,transf=transf.ipft.hm,targ=list(ni=dat$total))
#print(pes.subg.procedure[order(pes.subg.procedure$pred)],digits=6)
print(pes.procedure,digits=6)
print(pes.subg.procedure[1],digits=6);print(pes.subg.procedure[29],digits=6)
print(subganal.procedure,digits=4)
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion not assuming a common between-study variance component across subgroups}
#Calculating each subgroup summary proportion as an independent meta-analysis ignoring subgrouping
#Do not pool within-group estimates of tau-squared
pes.da.endoscopy=rma(yi,vi,data=ies.da,subset=procedure=="endoscopy",method="DL")
pes.da.microscopy=rma(yi,vi,data=ies.da,subset=procedure=="microscopy",method="DL")
pes.endoscopy=predict(pes.da.endoscopy,transf=transf.ipft.hm,targ=list(ni=dat$total))
pes.microscopy=predict(pes.da.microscopy,transf=transf.ipft.hm,targ=list(ni=dat$total))
dat.diffvar= data.frame(estimate=c(pes.da.endoscopy$b, pes.da.microscopy$b),
                        stderror=c(pes.da.endoscopy$se, pes.da.microscopy$se),
                        procedure = c("endoscopy","microscopy"), 
                        tau2=round(c(pes.da.endoscopy$tau2, pes.da.microscopy$tau2),3))
subganal.procedure=rma(estimate, sei=stderror, mods=~procedure, method="FE", data=dat.diffvar, digits=4)
pes.da.procedure=rma(estimate, sei=stderror, method="FE", data=dat.diffvar, digits=4) 
pes.procedure=predict(pes.da.procedure,transf=transf.ipft.hm,targ=list(ni=dat$total))
print(pes.endoscopy,digits=6);print(pes.da.endoscopy,digits=2)
print(pes.microscopy,digits=6);print(pes.da.microscopy,digits=2)
print(subganal.procedure,digits=2)
print(pes.procedure,digits=6)
##The authors used the FE model.
##The authors used the arcsine transformation to convert double arcsine transformed proportions back to proportions. The authors did not report the reason for doing so in their article.
##predict(pes.da.endoscopy,transf=transf.iarcsin)
##predict(pes.da.microscopy,transf=transf.iarcsin)
```
```{r Forest plot with metafor assuming a common variance component}
png("forestplotmetafor.png",width=1000,height=1000)
ies.summary=summary(ies.da,transf=transf.ipft,ni=dat$total)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author, dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.5),
       rows=c(36:20, 13:2),
       ylim=c(-2,41),
       xlim=c(-2,2.1),
       at=c(seq(from=0,to=0.5,by=0.1)), 
       refline=pes.procedure$pred,
       cex=1,
       font=6,
       main="Effect size by procedure (ME model)",
       xlab="Proportion",
       digits=6
       )
text(-2, 41,pos=4,cex=1,font=6,"Author(s), Year")
text(-2,c(14.5,37.5),pos=4, cex=1,font=6,c("Microscopy", "Endoscopy"))
text(c(-0.9,-0.6), 41,pos=4,cex=1,font=6,c("Cases", "Total"))
text(1.6,41,pos=4,font=6,cex=1,"Proportion [95% CI]")
text(-2,-3,pos=4,cex=0.8,bquote(paste("Overall")))
text(-2,18.5,pos=4,cex=0.8,bquote(paste("Subgroup")))
text(-2,0.5,pos=4,cex=0.8,bquote(paste("Subgroup")))
addpoly(pes.subg.procedure[1]$pred,ci.lb=pes.subg.procedure[1]$ci.lb,ci.ub=pes.subg.procedure[1]$ci.ub,row=18.5,digits=6,cex=0.8,mlab="")
addpoly(pes.subg.procedure[29]$pred,ci.lb=pes.subg.procedure[29]$ci.lb,ci.ub=pes.subg.procedure[29]$ci.ub,row=0.5,digits=6,cex=0.8,mlab="")
addpoly(pes.procedure$pred,ci.lb=pes.procedure$ci.lb,ci.ub=pes.procedure$ci.ub,row=-3,digits=6,cex=0.8,mlab="")
abline(h=-2)
dev.off()
```
```{r Forest plot with metafor not assuming a common variance component}
png("forestplotmetafor.png",width=1000,height=1000)
ies.summary=summary(ies.da,transf=transf.ipft,ni=dat$total)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author, dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.5),
       rows=c(36:20, 13:2),
       ylim=c(-2,41),
       xlim=c(-2,2.1),
       at=c(seq(from=0,to=0.5,by=0.1)), 
       refline=pes.procedure$pred,
       cex=1,
       font=6,
       main="Effect size by procedure (ME model)",
       xlab="Proportion",
       digits=6
       )
text(-2, 41,pos=4,cex=1,font=6,"Author(s), Year")
text(-2,c(14.5,37.5),pos=4, cex=1,font=6,c("Microscopy", "Endoscopy"))
text(c(-0.9,-0.6), 41,pos=4,cex=1,font=6,c("Cases", "Total"))
text(1.6,41,pos=4,font=6,cex=1,"Proportion [95% CI]")
text(-2,-3,pos=4,cex=0.8,bquote(paste("Overall")))
text(-2,18.5,pos=4,cex=0.8,bquote(paste("Subgroup")))
text(-2,0.5,pos=4,cex=0.8,bquote(paste("Subgroup")))
addpoly(pes.endoscopy$pred,ci.lb=pes.endoscopy$ci.lb,ci.ub=pes.endoscopy$ci.ub,row=18.5,digits=6,cex=0.8,mlab="")
addpoly(pes.microscopy$pred,ci.lb=pes.microscopy$ci.lb,ci.ub=pes.microscopy$ci.ub,row=0.5,digits=6,cex=0.8,mlab="")
addpoly(pes.procedure$pred,ci.lb=pes.procedure$ci.lb,ci.ub=pes.procedure$ci.ub,row=-3,digits=6,cex=0.8,mlab="")
abline(h=-2)
dev.off()
```
```{r Scatterplot for procedure}
#If you want the y-axis to be expressed as a double arcsine transformed proportion
subganal.proced=rma(yi,vi,data=ies.da,mods=~proced,method="DL")
preds.proced=predict(subganal.proced,newmods=c(0:2))
wi=1/sqrt(ies.da$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies.da$proced,ies.da$yi,cex=size,pch=1,las=1,xlab="Procedure", ylab="Double arcsine transformed proportions")
lines(0:2,preds.proced$pred,col="navy")
lines(0:2,preds.proced$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.proced$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(3)
text(ies.da$proced[ids],ies.da$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot for procedure}
#If you want the y-axis to be expressed as a proportion
subganal.proced=rma(yi,vi,data=ies.da,mods=~proced,method="DL")
preds.proced=predict(subganal.proced,newmods=c(0:2),transf=transf.ipft.hm,targ=list(ni=dat$total))
wi=1/sqrt(ies.da$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies.da$proced,transf.ipft.hm(ies.da$yi,targ=list(ni=dat$total)),cex=size,pch=1,las=1,xlab="Procedure", ylab="Proportions")
lines(0:2,preds.proced$pred,col="navy")
lines(0:2,preds.proced$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.proced$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(3)
text(ies.da$proced[ids],transf.ipft.hm(ies.da$yi,targ=list(ni=dat$total))[ids],ids,cex=0.9,pos=pos)
```
```{r Funnel plot}
#If you want the x-axis to be expressed as a double arcsine transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.da,yaxis="sei")
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.da,atransf=transf.ipft.hm,targ=list(ni=dat$total),yaxis="sei",xlab="Proportion")
```
```{r Trim and fill plot}
pes.trimfill=trimfill(pes.da)
#If you want the x-axis to be expressed as a double arcsine transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.trimfill)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.trimfill,atransf=transf.ipft.hm,targ=list(ni=dat$total),yaxis="sei",xlab="Proportion")
predict(pes.trimfill,transf=transf.ipft.hm,targ=list(ni=dat$total))
```
```{r Egger's regression test with double arcsine transformation}
regtest(pes.da,model="lm",predictor="sei")
```
```{r Rank correlation}
ranktest(pes.da)
```
```{r Failsafe N test}
fsn(yi,vi,data=ies.da)
```