```{r Installing required packages}
install.packages(c("metafor","meta","weightr"))#When you use knitr,delete this chunk and sure every code is executable (e.g. you may need to specify your working directory)
```
```{r Loading packages}
library(metafor)
library(meta)
```
```{r Reading in data}
dat=read.csv("D:/data/data_logit.csv",header=T,sep=",")
```
```{r Calculating overall summary proportion}
ies.logit=escalc(xi=cases,ni=total,measure="PLO",data=dat)
pes.logit=rma(yi,vi,data=ies.logit,method="DL",weighted=TRUE)
pes=predict(pes.logit,transf=transf.ilogit)
print(pes,digits=6);print(pes.logit,digits=4);confint(pes.logit,digits=2)
```
```{r Identifying outliers with residuals}
stud.res=rstudent(pes.logit)
abs.z=abs(stud.res$z)
stud.res[order(-abs.z)]
```
```{r Leave-one-out analysis}
l1o=leave1out(pes.logit)
yi=l1o$estimate;vi=l1o$se^2
forest(yi,vi,transf=transf.ilogit,slab=paste(dat$author,dat$year,sep=", "),xlab="Summary proportions leaving out each study",refline=pes$pred,digits=6)
abline(h=0.1)
L1O=leave1out(pes.logit,transf=transf.ilogit);print(L1O,digits=6)
```
```{r Baujat plot}
baujat(pes.logit,xlab="Contribution to Q-statistic", ylab="Influence on Summary Proportion")
```
```{r Diagnostic tests}
inf=influence(pes.logit)
print(inf);plot(inf)
```
```{r Removing outliers}
ies.logit.noutlier=escalc(xi=cases,ni=total,measure="PLO", data=dat[-c(2,8),])
pes.logit.noutlier=rma(yi,vi,data=ies.logit.noutlier,method="DL")
pes.noutlier=predict(pes.logit.noutlier,transf=transf.ilogit)
print(pes.noutlier,digits=6)
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion assuming a common between-study variance component across subgroups}
#Pool within-group estimates of tau-squared (between-study variance):0.4427 is the combined tau^2 yielded by pooling 0.93224 and 0.24743
#Residual heterogeneity is heterogeneity not explained by the covariate (Thompson and Sharp, 1999). The results of the Test for Residual Heterogeneity show that there is significant unexplained variance left between all effect sizes in the dataset, which can explain why R^2 shows 0%
#The category that is coded as 0 (ie Birth cohort) will become the reference category (represented by the intercept).The other category coded as 1 (ie Others) will be compared against the reference category.
#The value of the intercept is the logit-transformed summary(mean) effect size of the studies in the reference category (ie Birth cohort)
#The summary effect size of the studies in the other category(ie Others) equals to -7.9742+0.3452=-7.629
#To create multivariate model:subganal.sizedesign=rma(yi,vi,data=ies.logit,mods=~samplesize+studydesign,method="DL")
subganal.studydesign=rma(yi,vi,data=ies.logit,mods=~studydesign,method="DL")
pes.logit.birthcohort=rma(yi,vi,data=ies.logit,mods=~studydesign=="Others",method="DL")
pes.logit.others=rma(yi,vi,data=ies.logit,mods=~studydesign=="Birth cohort",method="DL")
pes.subg.studydesign=predict(subganal.studydesign,transf=transf.ilogit)
dat.samevar=data.frame(estimate=c((pes.logit.birthcohort$b)[1],(pes.logit.others$b)[1]),
                       stderror=c((pes.logit.birthcohort$se)[1],(pes.logit.others$se)[1]),
                       tau2=subganal.studydesign$tau2)
pes.logit.studydesign=rma(estimate,sei=stderror,method="DL",data=dat.samevar) 
pes.studydesign=predict(pes.logit.studydesign,transf=transf.ilogit)
#print(pes.subg.studydesign[order(pes.subg.studydesign$pred)],digits=6)
print(subganal.studydesign,digits=4)
print(pes.subg.studydesign[1],digits=6);print(pes.subg.studydesign[17],digits=6)
print(pes.studydesign,digits=6)
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion not assuming a common between-study variance component across subgroups}
#Do not pool within-group estimates of tau-squared
pes.logit.birthcohort=rma(yi,vi,data=ies.logit,subset=studydesign=="Birth cohort",method="DL")
pes.logit.others=rma(yi,vi,data=ies.logit,subset=studydesign=="Others",method="DL")
pes.birthcohort=predict(pes.logit.birthcohort,transf=transf.ilogit,digits=5)
pes.others=predict(pes.logit.others,transf=transf.ilogit,digits=5)
dat.diffvar=data.frame(estimate=c(pes.logit.birthcohort$b,pes.logit.others$b),
                       stderror=c(pes.logit.birthcohort$se,pes.logit.others$se),
                       studydesign=c("Birth cohort","Others"), 
                       tau2=round(c(pes.logit.birthcohort$tau2, pes.logit.others$tau2),3))
subganal.studydesign=rma(estimate,sei=stderror,mods=~studydesign,method="FE",data=dat.diffvar)
pes.logit.studydesign=rma(estimate,sei=stderror,method="FE",data=dat.diffvar)
pes.studydesign=predict(pes.logit.studydesign,transf=transf.ilogit)
print(pes.birthcohort,digits=6);print(pes.logit.birthcohort,digits=3)
print(pes.others,digits=6);print(pes.logit.others,digits=3)
print(subganal.studydesign,digits=3)
print(pes.studydesign,digits=6)
```
```{r Forest plot with metafor assuming a common variance component}
ies.summary=summary(ies.logit,transf=transf.ilogit,ni=dat$total)
png("forestplotmetafor.png",width=550,height=560)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author,dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.002,-0.001),
       rows=c(19:14, 8.5:-1.5),
       at=c(seq(from=0,to=0.004,by=0.001)), 
       refline=pes.studydesign$pred,
       ylim=c(-5,23),
       xlim=c(-0.005,0.005),
       bg="navy",
       cex=1,
       main="Effect Size by Study Design (Mixed-Effects Model)",
       xlab="Proportion",
       digits=4
       )
addpoly(pes.subg.studydesign[1]$pred,ci.lb=pes.subg.studydesign[1]$ci.lb,ci.ub=pes.subg.studydesign[1]$ci.ub,row=12.7,col="red",digits=5,cex=1.1)
addpoly(pes.subg.studydesign[17]$pred,ci.lb=pes.subg.studydesign[17]$ci.lb,ci.ub=pes.subg.studydesign[17]$ci.ub,row=-2.7,col="red",digits=5,cex=1.1)
addpoly(pes.studydesign$pred,ci.lb=pes.studydesign$ci.lb,ci.ub=pes.studydesign$ci.ub,row=-4.4,col="red",digits=5,cex=1.1)
text(-0.005,21.8,pos=4,cex=1.1,"Author, Year")
text(c(-0.0026,-0.0014),21.8,pos=4,cex=1.1,c("Cases", "Total"))
text(0.0023,21.8,pos=4,cex=1.1,font=1,"Proportion [95% CI]")
text(-0.005,c(9.7,20.2),pos=4, cex=1.1,c("Others", "Birth cohort"))
text(-0.005,-4.4,pos=4,cex=1.1,bquote(paste("Overall")))
text(-0.005,12.7,pos=4,cex=1.1,bquote(paste("Subgroup")))
text(-0.005,-2.7,pos=4,cex=1.1,bquote(paste("Subgroup")))
abline(h=-3.5)
dev.off()
```
```{r Forest plot with metafor not assuming a common variance component}
ies.summary=summary(ies.logit,transf=transf.ilogit,ni=dat$total)
png("forestplotmetafor.png",width=550,height=550)
par(cex=1,font=6)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       ylim=c(-5,23),
       xlim=c(-0.005,0.005),
       slab=paste(dat$author,dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.0019,-0.0005),
       ilab.pos=2,
       rows=c(19:14, 8.5:-1.5),
       at=c(seq(from=0,to=0.004,by=0.001)), 
       refline=pes.studydesign$pred,
       main="",
       xlab="Proportion (%)",
       digits=4
       )
par(cex=1.2,font=7)
addpoly(pes.birthcohort$pred,ci.lb=pes.birthcohort$ci.lb,ci.ub=pes.birthcohort$ci.ub,row=12.8,digits=5)
addpoly(pes.others$pred,ci.lb=pes.others$ci.lb,ci.ub=pes.others$ci.ub,row=-2.7,digits=5)
addpoly(pes.studydesign$pred,ci.lb=pes.studydesign$ci.lb,ci.ub=pes.studydesign$ci.ub,row=-4.6,digits=5)
par(cex=1.1,font=7)
text(-0.005,21.8,pos=4,"Study")
text(c(-0.0026,-0.0014),21.8,pos=4,c("Cases", "Total"))
text(0.0025,21.8,pos=4,"Proportion [95% CI]")
text(-0.005,c(9.7,20.2),pos=4,c("Others", "Birth cohort"))
par(cex=1,font=7)
text(-0.005,-4.6,pos=4,c("Overall"))
text(-0.005,12.8,pos=4,c("Subgroup"))
text(-0.005,-2.7,pos=4,c("Subgroup"))
abline(h=-3.7)
dev.off()
```
```{r Forest plot with meta assuming a common variance component}
#if assuming a common tau-squared, set tau.common=TRUE and prespecify the pooled tau-squared with tau.preset=sqrt(subganal.studydesign$tau2) (note it is tau not tau-squared).
#precision=1/(ies.logit$vi)
subganal.studydesign=rma(yi,vi,data=ies.logit,mods=~studydesign,method="DL")
pes.summary=metaprop(cases,
                     total,
                     authoryear,
                     data=dat,
                     #sortvar(precision)
                     byvar=studydesign,
                     sm="PLO",
                     method.ci="NAsm",
                     method.tau="DL",
                     incr=0.5,
                     allincr=FALSE,
                     addincr=FALSE,
                     tau.common=TRUE,
                     tau.preset=sqrt(subganal.studydesign$tau2),
                     title="")
png("forestplotmeta.png",width=700,height=600)
precison=sqrt(ies.logit$vi)
forest(pes.summary,
       #sortvar=precision,
       xlim = c(0,4), pscale =1000, #if proportions are too low, consider rescaling proportions
       rightcols=FALSE,
       leftcols = c("studlab","effect", "ci"),#"event", "n","w.random" 
       leftlabs = c("Study","Proportion", "95% C.I."),#"Cases", "Total","Weights"
       xlab = "Proportion (‰)", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="maroon", col.diamond.lines="maroon",
       comb.fixed=FALSE,
       lty.random=2, #lty.fixed=0,
       type.study="square",
       type.random="diamond",
       ff.random="bold", #ff.fixed="bold",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=TRUE,
       col.by="black",
       digits=4,
       digits.Q=0)
dev.off()
```
```{r Scatterplot for study design}
#Assuming a common between-study variance component across subgroups
#0.3452 is the coeffecient for the study design moderator;the pvals of QM and zval indicate this moderator is not significant
subganal.studesg=rma(yi,vi,data=ies.logit,mods=~studesg,method="DL")
preds.studesg=predict(subganal.studesg,newmods=c(0:2),transf=transf.ilogit)
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies.logit$studesg,transf.ilogit(ies.logit$yi),cex=size,pch=1,las=1,xlab="Study Design", ylab="Proportion")
lines(0:2,preds.studesg$pred,col="navy")
lines(0:2,preds.studesg$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.studesg$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(2)
text(ies.logit$studesg[ids],transf.ilogit(ies.logit$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot for sample size}
subganal.size=rma(yi,vi,data=ies.logit,mods=~size,method="DL")
preds.size=predict(subganal.size,newmods=c(0:2),transf=transf.ilogit)
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies.logit$size,transf.ilogit(ies.logit$yi),cex=size,xlab="Sample size", ylab="Proportion")
lines(0:2,preds.size$pred,col="navy")
lines(0:2,preds.size$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.size$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(2)
text(ies.logit$studesg[ids],transf.ilogit(ies.logit$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot for year}
metareg.year=rma(yi,vi,data=ies.logit,mods=~year,method="DL")
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.year=predict(metareg.year,newmods=c(1985:2020),transf=transf.ilogit)
plot(ies.logit$year,transf.ilogit(ies.logit$yi),cex=size,pch=1,xlab="Publication year", ylab="Proportion")
lines(1985:2020,preds.year$pred,col="navy")
lines(1985:2020,preds.year$ci.lb,lty="dashed",col="maroon")
lines(1985:2020,preds.year$ci.ub,lty="dashed",col="maroon")
ids=c(1:17)
pos=c(3)
text(ies.logit$year[ids],transf.ilogit(ies.logit$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Funnel plot}
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
funnel(pes.logit,yaxis="ni",refline=0)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
#funnel(pes.logit,atransf=transf.ilogit,yaxis="sei",xlab="Proportion",digits=c(5,0))
```
```{r Trim and fill plot}
pes.trimfill=trimfill(pes.logit)
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
funnel(pes.trimfill)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
#funnel(pes.trimfill,atransf=transf.ilogit,yaxis="sei",xlab="Proportion",digits=6)
predict(pes.trimfill,transf=transf.ilogit)
```
```{r Eggers regression test}
regtest(pes.logit,model="rma",predictor="sei")#warning: when using knitr, the "'" in the "Egger's" should be deleted
```
```{r Rank correlation}
ranktest(pes.logit)
```
```{r Vevea and Hedges Weight-Function Model}
weightfunct(ies.logit$yi,ies.logit$vi,steps=0.05)
```
```{r Failsafe N test}
fsn(yi,vi,data=ies.logit)
```