```{r Loading libraries}
library(randomNames)
library(metafor)
```
```{r Simulating a dataset}
set.seed(1)
randomNames(30,which.names="last")
author=randomNames(30,which.names="last")
year=sample(2000:2017,30,replace=T)
minsize=30
maxsize=200
minsample=0
maxsample=1
studies=data.frame(cases=runif(30,min=minsample,max=maxsample),total=sample(minsize:maxsize,30,replace=TRUE))
studies$cases=round(studies$cases * studies$total)
cases=studies$cases
total=studies$total
month=sample(1:36,30,replace=TRUE) #number of months of treatment before dropout
age=sample(18:99,30,replace=TRUE) #age
studies=cbind(author, year,cases, total, month, age)
write.csv(studies,file="simdat.csv")
```
```{r Reading in the dataset simulated}
dat=read.csv("simdat.csv",header=T,sep=",")
```
```{r Calculating individual effect sizes}
ies=escalc(xi=cases,ni=total,measure="PR",data=dat) 
```
```{r Meta-regression for month}
#If you want to analyze two or more moderators: mods=~month+age+...
metareg.month=rma(yi,vi,data=ies,mods=~month,method="REML",test="z")
print(metareg.month)
```
```{r Scatterplot for month}
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.month=predict(metareg.month,newmods=c(0:40))
plot(ies$month,ies$yi,cex=size,pch=1,xlab="Month", ylab="Proportion",las=1)
lines(0:40,preds.month$pred)
lines(0:40,preds.month$ci.lb,lty="dashed")
lines(0:40,preds.month$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies$month[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Meta-regression for year}
#If you want to analyze two or more moderators: mods=~month+age+...
metareg.year=rma(yi,vi,data=ies,mods=~year,method="REML",test="z")
print(metareg.year)
```
```{r Scatterplot for year}
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.year=predict(metareg.year,newmods=c(2000:2020))
plot(ies$year,ies$yi,cex=size,pch=1,xlab="Month", ylab="Proportion",las=1)
lines(2000:2020,preds.year$pred)
lines(2000:2020,preds.year$ci.lb,lty="dashed")
lines(2000:2020,preds.year$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies$year[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Calculating individual effect sizes with logit transformation}
ies.logit=escalc(xi=cases,ni=total,measure="PLO",data=dat)
```
```{r Meta-regression with logit transformation for age}
metareg.age=rma(yi,vi,data=ies.logit,mods=~age,method="REML")
print(metareg.age)
```
```{r Scatterplot with logit transformation for age}
#If you want the y-axis to be expressed as a proportion
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.age=predict(metareg.age,newmods=c(0:100),transf=transf.ilogit)
plot(ies.logit$age,transf.ilogit(ies.logit$yi),cex=size,pch=1,xlab="Age", ylab="Proportion",las=1)
lines(0:100,preds.age$pred)
lines(0:100,preds.age$ci.lb,lty="dashed")
lines(0:100,preds.age$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies.logit$age[ids],transf.ilogit(ies.logit$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot with logit transformation for age}
#If you want the y-axis to be expressed as a logit event rate
wi=1/sqrt(ies.logit$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.age=predict(metareg.age,newmods=c(0:100))
plot(ies.logit$age,ies.logit$yi,cex=size,pch=1,xlab="Age", ylab="Logit event rate",las=1)
lines(0:100,preds.age$pred)
lines(0:100,preds.age$ci.lb,lty="dashed")
lines(0:100,preds.age$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies.logit$age[ids],ies.logit$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Calculating individual effect sizes with double arcsine transformation}
ies.da=escalc(measure="PFT",xi=cases,ni=total,data=dat, add=0)
```
```{r Meta-regression with double arcsine transformation for month}
metareg.month=rma(yi,vi,data=ies.da,mods=~month,method="REML",test="z")
print(metareg.month)
```
```{r Scatterplot with double arcsine transformation for month}
#If you want the y-axis to be expressed as a proportion
wi=1/sqrt(ies.da$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.month=predict(metareg.month,newmods=c(0:40),transf=transf.ipft.hm,targ=list(ni=dat$total))
plot(ies.da$month,transf.ipft.hm(ies.da$yi,targ=list(ni=dat$total)),cex=size,pch=1,xlab="Month", ylab="Proportion",las=1)
lines(0:40,preds.month$pred)
lines(0:40,preds.month$ci.lb,lty="dashed")
lines(0:40,preds.month$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(3)
text(ies.da$month[ids],transf.ipft.hm(ies.da$yi,targ=list(ni=dat$total))[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot with double arcsine transformation for month}
#If you want the y-axis to be expressed as a double arcsine transformed proportion
wi=1/sqrt(ies.da$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.month=predict(metareg.month,newmods=c(0:40))
plot(ies.da$month,ies.da$yi,cex=size,pch=1,xlab="Month", ylab="Double arcsine transformed proportions",las=1)
lines(0:40,preds.month$pred)
lines(0:40,preds.month$ci.lb,lty="dashed")
lines(0:40,preds.month$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(3)
text(ies.da$month[ids],ies.da$yi[ids],ids,cex=0.9,pos=pos)
```