```{r Installing required packages}
install.packages(c("metafor","meta"))#Already installed
```
```{r Loading packages}
library(metafor)
library(meta)
```
```{r Reading in data}
dat=read.csv("D:/data/data_none.csv",header=T,sep=",")
```
```{r Calculating overall summary proportion}
ies=escalc(xi=cases,ni=total,measure="PR",data=dat) 
pes=rma(yi,vi,data=ies,method="DL",weighted=TRUE)
print(pes,digits=6);confint(pes)
```
```{r Identifying outliers with residuals}
stud.res=rstudent(pes)
abs.z=abs(stud.res$z)
stud.res[order(-abs.z)]
```
```{r Leave-one-out analysis}
l1o=leave1out(pes)
yi=l1o$estimate;vi=l1o$se^2
forest(yi,vi,slab=paste(dat$author,dat$year,sep=", "),xlab="Summary proportions leaving out each study",refline=pes$b,digits=6)
L1O=leave1out(pes);print(L1O,digits=6)
```
```{r Baujat plot}
baujat(pes)
```
```{r Diagnostic tests}
inf=influence(pes)
print(inf);plot(inf)
```
```{r Removing outliers}
ies.noutlier=escalc(xi=cases,ni=total,measure="PR", data=dat[-c(3,11,12),])
pes.noutlier=rma(yi,vi,data=ies.noutlier,method="DL",weighted=TRUE)
print(pes.noutlier)
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion assuming a common between-study variance component across subgroups}
#Pool within-group estimates of tau-squared (between-study variance)
subganal.province=rma(yi,vi,data=ies,mods=~province,method="DL")
pes.guangdong=rma(yi,vi,data=ies,mods=~province=="Guangxi",method="DL")
pes.guangxi=rma(yi,vi,data=ies,mods=~province=="Guangdong",method="DL")
pes.subg.province=predict(subganal.province)
dat.samevar=data.frame(estimate=c((pes.guangdong$b)[1],(pes.guangxi$b)[1]),
                       stderror=c((pes.guangdong$se)[1],(pes.guangxi$se)[1]),
                       tau2=subganal.province$tau2)
pes.province=rma(estimate,sei=stderror,method="FE",data=dat.samevar) #method="FE or other RE estimators"
pes.province=predict(pes.province)
#print(pes.subg.province[order(pes.subg.province$pred)],digits=4)
print(subganal.province,digits=4)
print(pes.subg.province[1],digits=4);print(pes.subg.province[19],digits=4)
print(pes.province,digits=4) 
```
```{r Calculating subgroup summary proportions, conducting subgroup analysis, and recalculating summary proportion not assuming a common among-study variance component across subgroups}
#Calculating each subgroup summary proportion as an independent meta-analysis
#Do not pool within-group estimates of tau-squared. This is the option used by RevMan.
pes.guangdong=rma(yi,vi,data=ies,subset=province=="Guangdong",method="DL")
pes.guangxi=rma(yi,vi,data=ies,subset=province=="Guangxi",method="DL")
dat.diffvar= data.frame(estimate=c(pes.guangdong$b, pes.guangxi$b),
                        stderror=c(pes.guangdong$se, pes.guangxi$se),
                        province = c("Guangdong","Guangxi"), 
                        tau2=round(c(pes.guangdong$tau2, pes.guangxi$tau2),3))
subganal.province=rma(estimate, sei=stderror, mods=~province, method="FE", data=dat.diffvar)
pes.province=rma(estimate, sei=stderror, method="FE", data=dat.diffvar)
pes.province=predict(pes.province)
print(pes.guangdong,digits=5);confint(pes.guangdong,digits=5)
print(pes.guangxi,digits=5);confint(pes.guangxi,digits=5)
print(subganal.province,digits=5)
print(pes.province,digits=5)
```
```{r Forest plot with metafor assuming a common variance component}
ies.summary=summary(ies,ni=dat$total)
png("forestplotmetafor.png",width=500,height=500)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author, dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.4),
       rows=c(25:13,7.6:2.6),
       at=c(seq(from=0,to=1.1,by=0.2)), 
       refline=pes.province$pred,
       ylim=c(-2,30),
       xlim=c(-2,2.1),
       cex=0.8,
       font=6,
       main="Effect size by province (ME Model)",
       xlab="Proportion",
       digits=3
       )
text(-2, 29,pos=4,cex=0.8,font=6,"Author(s), Year")
text(-2,c(8.9,26.3),pos=4, cex=0.8,font=6,c("Guangxi", "Guangdong"))
text(c(-1, -0.6), 29,pos=4,cex=0.8,font=6,c("Cases", "Total"))
text(1.25,29,pos=4,font=6,cex=0.8,"Proportion [95% CI]")
text(-2,-1,pos=4,cex=0.8,font=1,bquote(paste("Overall")))
text(-2,11.4,pos=4,cex=0.8,font=1,bquote(paste("Subgroup")))
text(-2,1.1,pos=4,cex=0.8,font=3,bquote(paste("Subgroup")))
addpoly(pes.subg.province[1]$pred,ci.lb=pes.subg.province[1]$ci.lb,ci.ub=pes.subg.province[1]$ci.ub,row=11.4,cex=0.8,mlab="",digits=3)
addpoly(pes.subg.province[19]$pred,ci.lb=pes.subg.province[19]$ci.lb,ci.ub=pes.subg.province[19]$ci.ub,row=1.1,cex=0.8,mlab="",digits=3)
addpoly(pes.province$pred,ci.lb=pes.province$ci.lb,ci.ub=pes.province$ci.ub,row=-1,cex=0.8,mlab="",digits=3)
abline(h=0)
dev.off()
```
```{r Forest plot with metafor not assuming a common variance component}
#If you want to create the forest plot manually, use the forest function in the metafor package. Numerical values in the following code are for demonstration purposes only. You need to change these values according to your data.
ies.summary=summary(ies,ni=dat$total)
png("forestplotmetafor.png",width=500,height=500)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author, dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.4),
       rows=c(25:13,7.6:2.6),
       at=c(seq(from=0,to=1.1,by=0.2)), 
       refline=pes.province$pred,
       ylim=c(-2,30),
       xlim=c(-2,2.1),
       cex=0.8,
       font=6,
       main="Effect size by province (ME Model)",
       xlab="Proportion",
       digits=3
       )
text(-2, 29,pos=4,cex=0.8,font=6,"Author(s), Year")
text(-2,c(8.9,26.3),pos=4, cex=0.8,font=6,c("Guangxi", "Guangdong"))
text(c(-1, -0.6), 29,pos=4,cex=0.8,font=6,c("Cases", "Total"))
text(1.25,29,pos=4,font=6,cex=0.8,"Proportion [95% CI]")
text(-2,-1,pos=4,cex=0.8,font=1,bquote(paste("Overall")))
text(-2,11.4,pos=4,cex=0.8,font=1,bquote(paste("Subgroup")))
text(-2,1.1,pos=4,cex=0.8,font=3,bquote(paste("Subgroup")))
addpoly(pes.guangdong,row=11.4,cex=0.8,mlab="",digits=3)
addpoly(pes.guangxi,row=1.1,cex=0.8,mlab="",digits=3)
addpoly(pes.province$pred,ci.lb=pes.province$ci.lb,ci.ub=pes.province$ci.ub,row=-1,cex=0.8,mlab="",digits=3)
abline(h=0)
dev.off()
```
```{r Forest plot with meta assuming a common variance component}
subganal.province=rma(yi,vi,data=ies,mods=~province,method="DL")
pes.summary=metaprop(cases,
                     total,
                     author,
                     data=dat,
                     byvar=province,
                     sm="PRAW",
                     method.ci="NAsm",
                     method.tau="DL",
                     incr=0.5,
                     allincr=FALSE,
                     addincr=FALSE,
                     tau.common=TRUE,
                     tau.preset=sqrt(subganal.province$tau2),
                     title="")
png("forestplotmeta.png",width=1000,height=1000)
forest(pes.summary,
       xlim = c(0,1), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey",
       digits=4)
dev.off()
```
```{r Scatterplot for province}
subganal.prov=rma(yi,vi,data=ies,mods=~prov,method="DL",weighted=TRUE)
preds.prov=predict(subganal.prov,newmods=c(0:2))
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies$prov,ies$yi,cex=size,pch=1,las=1,xlab="Province", ylab="Proportion")
lines(0:2,preds.prov$pred,col="navy")
lines(0:2,preds.prov$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.prov$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(1)
text(ies$prov[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Funnel plot}
funnel(pes)
```
```{r Trim and fill plot}
pes.trimfill=trimfill(pes)
funnel(pes.trimfill)
print(pes.trimfill)
```
```{r Egger's regression test}
regtest(pes,model="lm",predictor="sei")
```
```{r Rank correlation}
ranktest(pes)
```
```{r Failsafe N test}
fsn(yi,vi,data=ies)
```