```{r Loading libraries}
library(randomNames)
library(metafor)
```
```{r simulating a dataset}
set.seed(1)
randomNames(30,which.names="last")
author=randomNames(30,which.names="last")
year=sample(2000:2017,30,replace=T)
minsize=30
maxsize=200
minsample=0
maxsample=1
studies=data.frame(cases=runif(30,min=minsample,max=maxsample),total=sample(minsize:maxsize,30,replace=TRUE))
studies$cases=round(studies$cases * studies$total)
cases=studies$cases
total=studies$total
moderator1=sample(1:36,30,replace=TRUE) #number of months of treatment before dropout
moderator2=sample(18:99,30,replace=TRUE) #age
studies=cbind(author, year,cases, total, moderator1, moderator2)
write.csv(studies,file="simdat.csv")
```
```{r Reading in the simulated data}
dat=read.csv("simdat.csv",header=T,sep=",")
```
```{r Calculating individual effect sizes}
ies=escalc(xi=cases,ni=total,measure="PR",data=dat) 
```
```{r Meta-regression}
#If you want to select two or more moderators: mods=~ moderator1+ moderator2+ moderator3
metareg.mod1=rma(yi,vi,data=ies,mods=~moderator1,method="REML",test="z")
print(metareg.mod1)
```
```{r Scatterplot}
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.mod1=predict(metareg.mod1,newmods=c(0:40))
plot(ies$moderator1,ies$yi,cex=size,pch=1,xlab="Moderator 1", ylab="Proportion",las=1)
lines(0:40,preds.mod1$pred)
lines(0:40,preds.mod1$ci.lb,lty="dashed")
lines(0:40,preds.mod1$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies$moderator1[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Calculating individual effect sizes with logit transformation}
ies=escalc(xi=cases,ni=total,measure="PLO",data=dat)
```
```{r Meta-regression with logit transformation}
metareg.mod1=rma(yi,vi,data=ies,mods=~moderator1,method="REML",test="z")
print(metareg.mod1)
```
```{r Scatterplot with logit transformed data}
#If you want the y-axis to be expressed as a proportion
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.mod1=predict(metareg.mod1,newmods=c(0:40),transf=transf.ilogit)
plot(ies$moderator1,transf.ilogit(ies$yi),cex=size,pch=1,xlab="Moderator 1", ylab="Proportion",las=1)
lines(0:40,preds.mod1$pred)
lines(0:40,preds.mod1$ci.lb,lty="dashed")
lines(0:40,preds.mod1$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies$moderator1[ids],transf.ilogit(ies$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot with logit transformed data}
#If you want the y-axis to be expressed as a logit event rate
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.mod1=predict(metareg.mod1,newmods=c(0:40))
plot(ies$moderator1,ies$yi,cex=size,pch=1,xlab="Moderator 1", ylab="Logit event rate",las=1)
lines(0:40,preds.mod1$pred)
lines(0:40,preds.mod1$ci.lb,lty="dashed")
lines(0:40,preds.mod1$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(1)
text(ies$moderator1[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Calculating individual effect sizes with Freeman-Tukey double arcsine transformation}
ies=escalc(measure="PFT",xi=cases,ni=total,data=dat, add=0)
```
```{r Meta-regression with double arcsine transformation}
metareg.mod1=rma(yi,vi,data=ies,mods=~moderator1,method="REML",test="z")
print(metareg.mod1)
```
```{r Scatterplot with double arcsine transformed data}
#If you want the y-axis to be expressed as a proportion
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.mod1=predict(metareg.mod1,newmods=c(0:40),transf=transf.ipft.hm,targ=list(ni=dat$total))
plot(ies$moderator1,transf.ipft.hm(ies$yi,targ=list(ni=dat$total)),cex=size,pch=1,xlab="Moderator 1", ylab="Proportion",las=1)
lines(0:40,preds.mod1$pred)
lines(0:40,preds.mod1$ci.lb,lty="dashed")
lines(0:40,preds.mod1$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(3)
text(ies$moderator1[ids],transf.ipft.hm(ies$yi,targ=list(ni=dat$total))[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot with double arcsine transformed data}
#If you want the y-axis to be expressed as a double arcsine transformed proportion
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
preds.mod1=predict(metareg.mod1,newmods=c(0:40))
plot(ies$moderator1,ies$yi,cex=size,pch=1,xlab="Moderator 1", ylab="Double arcsine transformed proportion",las=1)
lines(0:40,preds.mod1$pred)
lines(0:40,preds.mod1$ci.lb,lty="dashed")
lines(0:40,preds.mod1$ci.ub,lty="dashed")
ids=c(1:6)
pos=c(3)
text(ies$moderator1[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```