```{r Installing required packages}
install.packages(c("metafor","meta","weightr"))
```
```{r Loading packages}
library(metafor)
library(meta)
library(weightr)
```
```{r Reading in data}
dat=read.csv("data.csv",header=T,sep=",")
```
```{r Calculating overall summary proportion}
ies=escalc(xi=cases,ni=total,measure="PLO",data=dat)
pes.transf=rma(yi,vi,data=ies,method="DL",weighted=TRUE)
pes=predict(pes.transf,transf=transf.ilogit)
print(pes);print(pes.transf);confint(pes.transf)
```
```{r Calculating subgroup summary proportions according to moderator a}
pes.transf.mal1=rma(yi,vi,data=ies,subset=moderatora=="level1",method="DL")
pes.transf.mal2=rma(yi,vi,data=ies,subset=moderatora=="level2",method="DL")
pes.mal1=predict(pes.transf.mal1,transf=transf.ilogit)
pes.mal2=predict(pes.transf.mal2,transf=transf.ilogit)
print(pes.mal1);print(pes.transf.mal1);confint(pes.transf.mal1)
print(pes.mal2);print(pes.transf.mal2);confint(pes.transf.mal2)
```
```{r Identifying outliers with residuals}
stud.res=rstudent(pes.transf)
abs.z=abs(stud.res$z)
stud.res[order(-abs.z)]
```
```{r Leave-one-out analysis}
pes.leave1out=leave1out(pes.transf,transf=transf.ilogit)
print(pes.leave1out)
```
```{r Baujat plot with logit transformation}
baujat(pes.transf)
```
```{r Diagnostic tests with logit transformation}
inf=influence(pes.transf)
print(inf);plot(inf)
```
```{r Removing outliers}
ies.noutlier=escalc(xi=cases,ni=total,measure="PLO", data=dat[-c(2,3),])
pes.transf.noutlier=rma(yi,vi,data=ies.noutlier,method="DL",weighted=TRUE)
pes.noutlier=predict(pes.transf.noutlier,transf=transf.ilogit)
print(pes.noutlier,digits=5)
```
```{r Forest plot with logit transformation using metafor}
#If you want to create the forest plot manually, use the forest function in the metafor package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
png("forestplot.png",width=1000,height=1000)
ies.summary=summary(ies,transf=transf.ilogit,ni=dat$total)
forest(ies.summary$yi,
       ci.lb=ies.summary$ci.lb,ci.ub=ies.summary$ci.ub,
       slab=paste(dat$author,dat$year, sep=", "),
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.002,-0.001),
       rows=c(19:14, 8.5:-1.5),
       at=c(seq(from=0,to=0.004,by=0.001)), 
       refline=pes$pred,
       ylim=c(-5,24),
       xlim=c(-0.005,0.005),
       cex=1,
       font=6,
       main="Effect size by moderator A (RE Model)",
       xlab="Proportion"
       )
text(-0.005, 23,pos=4,cex=1,font=6,"Author(s), Year")
text(-0.005,c(10,20.5),pos=4, cex=1,font=6,c("mal2", "mal1"))
text(c(-0.0022,-0.0012), 23,pos=4,cex=1,font=6,c("Cases", "Total"))
text(0.003,23,pos=4,font=6,cex=1,"Proportion [95% CI]")
addpoly(pes.mal1$pred,ci.lb=pes.mal1$ci.lb,ci.ub=pes.mal1$ci.ub,row=12.7,cex=0.8,mlab="")
addpoly(pes.mal2$pred,ci.lb=pes.mal2$ci.lb,ci.ub=pes.mal2$ci.ub,row=-2.5,cex=0.8,mlab="")
addpoly(pes$pred,ci.lb=pes$ci.lb,ci.ub=pes$ci.ub,row=-5,cex=0.8,mlab="")
text(-0.005,-5,pos=4,cex=0.8, bquote(paste("All studies (Q = ",.(formatC(pes.transf$QE, format="f")), ", df = ", .(pes.transf$k - pes.transf$p),", p = ", .(formatC(pes.transf$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.transf$I2, format="f")), "%",")")))
text(-0.005,12.7,pos=4,cex=0.8, bquote(paste("Subtotal(Q = ",.(formatC(pes.transf.mal1$QE, format="f")), ", df = ", .(pes.transf.mal1$k - pes.transf.mal1$p),", p = ", .(formatC(pes.transf.mal1$QEp, format="f")),"; ", I^2, " = ",.(formatC(pes.transf.mal1$I2, format="f")), "%",")")))
text(-0.005,-2.8,pos=4,cex=0.8, bquote(paste("Subtotal(Q = ",.(formatC(pes.transf.mal2$QE, format="f")),", df = ", .(pes.transf.mal2$k - pes.transf.mal2$p), ", p = ", .(formatC(pes.transf.mal2$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.transf.mal2$I2, format="f")), "%",")")))
abline(h=-4)
dev.off()
```
```{r Forest plot using metaprop}
#If you want to create the forest plot automatically, use the forest function in the meta package. Numerical values in the following code are for demonstration purposes only. You need to change these values according to your dataset.
pes.forest=metaprop(cases,total,author,data=dat,byvar=moderatora,sm="PLO",method.ci="NAsm",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,title="")
png("forestplot.png",width=1000,height=1000)
forest(pes.forest,
       xlim = c(0,0.005), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey")
dev.off()
```
```{r Subgroup analysis assuming a common among-study variance component across subgroups}
#Pool within-group estimates of tau-squared.
subganal.moderatora=rma(yi,vi,data=ies,mods=~moderatora,method="DL")
print(subganal.moderatora)
```
```{r Subgroup analysis not assuming a common among-study variance component across subgroups}
#Do not pool within-group estimates of tau-squared. This is the option used by RevMan.
dat.diffvar= data.frame(estimate=c(pes.transf.mal1$b, pes.transf.mal2$b),stderror=c(pes.transf.mal1$se, pes.transf.mal2$se),moderatora=c("mal1","mal2"),tau2=round(c(pes.transf.mal1$tau2, pes.transf.mal2$tau2),3))
subganal.moderatora=rma(estimate,sei=stderror,mods=~moderatora,method="FE",data=dat.diffvar)
print(subganal.moderatora)
```
```{r Scatterplot for catergorical moderators}
#If you want the y-axis to be expressed as a proportion
subganal.moda=rma(yi,vi,data=ies,mods=~moda,method="REML")
preds.moda=predict(subganal.moda,newmods=c(0:2),transf=transf.ilogit)
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies$moda,transf.ilogit(ies$yi),cex=size,pch=1,las=1,xlab="Moderator A", ylab="Proportion")
lines(0:2,preds.moda$pred,col="navy")
lines(0:2,preds.moda$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.moda$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(2)
text(ies$moda[ids],transf.ilogit(ies$yi)[ids],ids,cex=0.9,pos=pos)
```
```{r Scatterplot for catergorical moderators}
#If you want the y-axis to be expressed as a logit event rate
subganal.moda=rma(yi,vi,data=ies,mods=~moda,method="REML")
preds.moda=predict(subganal.moda,newmods=c(0:2))
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies$moda,ies$yi,cex=moda,pch=1,las=1,xlab="Moderator A", ylab="Logit event rate")
lines(0:2,preds.moda$pred,col="navy")
lines(0:2,preds.moda$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.moda$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(2)
text(ies$moda[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Funnel plot}
png("funnel.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.transf,yaxis="sei")
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.transf,atransf=transf.ilogit,yaxis="sei",xlab="Proportion")
dev.off()
```
```{r Trim and fill plot}
pes.trimfill=trimfill(pes.transf)
png("trimfill.png",width=1000,height=1000)
#If you want the x-axis to be expressed as a logit transformed proportion, then remove the "#" sign before the following line.
#funnel(pes.trimfill)
#If you want the x-axis to be expressed as a proportion, then remove the "#" sign before the following line.
funnel(pes.trimfill,atransf=transf.ilogit,yaxis="sei",xlab="Proportion")
dev.off()
predict(pes.trimfill,transf=transf.ilogit)
```
```{r Egger's regression test}
regtest(pes.transf,model="lm",predictor="sei")
```
```{r Rank correlation}
ranktest(pes.transf)
```
```{r Vevea and Hedges Weight-Function Model}
weightfunct(ies$yi,ies$vi,steps=0.05)
```
```{r Failsafe N test}
fsn(yi,vi,data=ies)
```