```{r Installing required packages}
install.packages(c("metafor","meta","weightr"))
```
```{r Loading packages}
library(metafor)
library(meta)
library(weightr)
```
```{r Reading in data}
dat=read.csv("data.csv",header=T,sep=",")
```
```{r Calculating overall summary proportion}
ies=escalc(xi=cases,ni=total,measure="PR",data=dat)
pes=rma(yi,vi,data=ies,method="DL",weighted=TRUE, slab=paste(author, year, sep=", "))
print(pes);confint(pes)
```
```{r Calculating subgroup summary proportions according to moderator a}
pes.mal1=rma(yi,vi,data=ies,subset=moderatora=="level1",method="DL")
pes.mal2=rma(yi,vi,data=ies,subset=moderatora=="level2",method="DL")
print(pes.mal1);confint(pes.mal1)
print(pes.mal2);confint(pes.mal2)
```
```{r Leave-one-out analysis}
leave1out(pes)
```
```{r Baujat plot}
baujat(pes)
```
```{r Diagnostic tests with logit transformation}
inf=influence(pes)
print(inf);plot(inf)
```
```{r Removing outliers}
ies.noutlier=escalc(xi=cases,ni=total,measure="PR", data=dat[-c(3,11,12),])
pes.noutlier=rma(yi,vi,data=ies.noutlier,method="DL",weighted=TRUE)
print(pes.noutlier)
```
```{r Forest plot using metafor}
#If you want to create the forest plot manually, use the forest function in the metafor package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
png("forestplot.png",width=1000,height=1000)
forest(pes,
       ilab=cbind(data=dat$cases, dat$total),
       ilab.xpos=c(-0.8, -0.4),
       rows=c(25:13,7.6:2.6),
       at=c(seq(from=0,to=1.1,by=0.2)),  
       refline=pes$b, 
       ylim=c(-2,30), 
       xlim=c(-2,2.1), 
       cex=0.8, 
       font=6,
       main="Effect size by moderator A (RE Model)",
       xlab="Proportion"
       )
text(-2, 29,pos=4,cex=0.8,font=6,"Author(s), Year")
text(-2,c(8.9,26.3),pos=4, cex=0.8,font=6,c("mal2", "mal1")) 
text(c(-1, -0.6), 29,pos=4,cex=0.8,font=6,c("Cases", "Total"))
text(1.65,29,pos=4,font=6,cex=0.8,"Proportion [95% CI]")
text(-2,-1.1,pos=4,cex=0.8,font=1, bquote(paste("All studies(Q = ",.(formatC(pes$QE, format="f")), ", df = ", .(pes$k - pes$p),", p = ", .(formatC(pes$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes$I2, format="f")), "%",")")))
text(-2,11.4,pos=4,cex=0.8,font=1, bquote(paste("Subtotal(Q = ",.(formatC(pes.mal1$QE, format="f")), ", df = ", .(pes.mal1$k - pes.mal1$p),", p = ", .(formatC(pes.mal1$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.mal1$I2, format="f")), "%",")")))
text(-2,1.1,pos=4,cex=0.8,font=3, bquote(paste("Subtotal(Q = ",.(formatC(pes.mal2$QE, format="f")),", df = ", .(pes.mal2$k - pes.mal2$p), ", p = ", .(formatC(pes.mal2$QEp, format="f")), "; ", I^2, " = ",.(formatC(pes.mal2$I2, format="f")), "%",")")))
addpoly(pes.mal1, row=11.4, cex=0.8,font=1, mlab="")
addpoly(pes.mal2, row=1.1, cex=0.8, font=1, mlab="")
dev.off()
```
```{r Forest plot using metaprop}
#If you want to create the forest plot automatically, use the forest function in the meta package. Numerical values in the following code are for demonstration purposes only. You need to respecify these values according to your dataset.
pes.forest=metaprop(cases,total,author,data=dat,byvar=moderatora,sm="PRAW",method.ci="NAsm",method.tau="DL",incr=0.5,allincr=FALSE,addincr=FALSE,title="")
png("forestplot.png",width=1000,height=1000)
forest(pes.forest,
       xlim = c(0,1), pscale =1, 
       rightcols=c("effect", "ci","w.random"),
       rightlabs=c("Proportion", "95% C.I.","Weights"),
       leftcols = c("studlab", "event", "n"), 
       leftlabs = c("Study", "Cases", "Total"),
       xlab = "Prevalence", 
       fs.xlab=12,
       fs.study=12,
       fs.study.lables=12,
       fs.heading=12,
       squaresize = 0.5, col.square="navy", col.square.lines="navy",
       col.diamond="navy", col.diamond.lines="navy",
       comb.fixed=FALSE,
       lty.fixed=0,
       lty.random=2, 
       type.study="square",
       type.random="diamond",
       ff.fixed="bold.italic",
       ff.random="bold.italic",
       hetlab = "Heterogeneity:",
       fs.hetstat=10,
       smlab="",
       print.Q=TRUE,
       print.pval.Q=TRUE,
       print.I2=TRUE,
       print.tau2=FALSE,
       col.by="grey")
dev.off()
```
```{r Subgroup analysis assuming a common among-study variance component across subgroups}
#Pool within-group estimates of tau-squared.
subganal.moderatora=rma(yi,vi,data=ies,mods=~moderatora,method="DL")
print(subganal.moderatora)
```
```{r Subgroup analysis not assuming a common among-study variance component across subgroups}
#Do not pool within-group estimates of tau-squared. This is the option used by RevMan.
dat.diffvar= data.frame(estimate=c(pes.mal1$b, pes.mal2$b),stderror=c(pes.mal1$se, pes.mal2$se),moderatora= c("mal1","mal2"), tau2=round(c(pes.mal1$tau2, pes.mal2$tau2),3))
subganal.moderatora=rma(estimate,sei=stderror,mods=~moderatora,method="FE",data=dat.diffvar)
print(subganal.moderatora)
```
```{r Scatterplot for catergorical moderators}
subganal.moda=rma(yi,vi,data=ies,mods=~moda,method="DL",weighted=TRUE)
preds.moda=predict(subganal.moda,newmods=c(0:2))
wi=1/sqrt(ies$vi)
size=1+3*(wi-min(wi))/(max(wi)-min(wi))
plot(ies$moda,ies$yi,cex=size,pch=1,las=1,xlab="Moderator A", ylab="Proportion")
lines(0:2,preds.moda$pred,col="navy")
lines(0:2,preds.moda$ci.lb,lty="dashed",col="maroon")
lines(0:2,preds.moda$ci.ub,lty="dashed",col="maroon")
ids=c(1:6)
pos=c(1)
text(ies$moda[ids],ies$yi[ids],ids,cex=0.9,pos=pos)
```
```{r Funnel plot}
png("funnel.png",width=1000,height=1000)
funnel(pes)
dev.off()
```
```{r Trim and fill plot}
png("trimfill.png",width=1000,height=1000)
pes.trimfill=trimfill(pes)
funnel(pes.trimfill)
dev.off()
print(pes.trimfill)
```
```{r Egger's regression test}
regtest(pes,model="lm",predictor="sei")
```
```{r Rank correlation}
ranktest(pes)
```
```{r Vevea and Hedges Weight-Function Model}
weightfunct(ies$yi,ies$vi,steps=0.05) 
```
```{r Failsafe N test}
fsn(yi,vi,data=ies)
```